### ISSUE TITLE
Problem with multytouch

### ISSUE THREAD

**Issue by andrei-turtsevich** [janishar/PlaceHolderView#107]
App crash, when tap to view and long tap to card simultaneously.

**Comment by janishar** [comment]
@AndreyTurcevich can you post the stack trace?

**Comment by andrei-turtsevich** [comment]
@janishar 
E/InputEventReceiver: Exception dispatching input event.
E/MessageQueue-JNI: Exception in MessageQueue callback: handleReceiveCallback
E/MessageQueue-JNI: java.lang.IllegalArgumentException: pointerIndex out of range
                        at android.view.MotionEvent.nativeGetAxisValue(Native Method)
                        at android.view.MotionEvent.getX(MotionEvent.java:2139)
                        at com.lorentzos.flingswipe.FlingCardListener.onTouch(FlingCardListener.java:78)
                        at android.view.View.dispatchTouchEvent(View.java:9951)
                        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2665)
                        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2344)
                        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2671)
                        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2301)
                        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2693)
                        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2301)
                        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2671)
                        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
                        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2671)
                        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
                        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2671)
                        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
                        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2671)
                        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
                        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2671)
                        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
                        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2671)
                        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
                        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2671)
                        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
                        at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:414)
                        at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1810)
                        at android.app.Activity.dispatchTouchEvent(Activity.java:3196)
                        at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:68)
                        at com.android.tools.profiler.support.event.WindowProfilerCallback.dispatchTouchEvent(WindowProfilerCallback.java:69)
                        at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:376)
                        at android.view.View.dispatchPointerEvent(View.java:10177)
                        at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4492)
                        at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4357)
                        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3897)
                        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3950)
                        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3916)
                        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4043)
                        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3924)
                        at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4100)
                        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3897)
                        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3950)
                        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3916)
                        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3924)
                        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3897)
                        at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6268)
                        at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6242)
                        at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6203)
                        at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6374)
                        at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:187)
                        at android.os.MessageQueue.nativePollOnce(Native Method)
                        at android.os.MessageQueue.next(MessageQueue.java:323)
                        at android.os.Looper.loop(Looper.java:142)
                        at android.app.ActivityThread.main(ActivityThread.java:6342)
                        at java.lang.reflect.Method.invoke(Native Method)
                    	at co
D/AndroidRuntime: Shutting down VM
E/AndroidRuntime: FATAL EXCEPTION: main
                  java.lang.IllegalArgumentException: pointerIndex out of range
                      at android.view.MotionEvent.nativeGetAxisValue(Native Method)
                      at android.view.MotionEvent.getX(MotionEvent.java:2139)
                      at com.lorentzos.flingswipe.FlingCardListener.onTouch(FlingCardListener.java:78)
                      at android.view.View.dispatchTouchEvent(View.java:9951)
                      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2665)
                      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2344)
                      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2671)
                      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2301)
                      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2693)
                      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2301)
                      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2671)
                      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
                      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2671)
                      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
                      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2671)
                      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
                      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2671)
                      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
                      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2671)
                      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
                      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2671)
                      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
                      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2671)
                      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
                      at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:414)
                      at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1810)
                      at android.app.Activity.dispatchTouchEvent(Activity.java:3196)
                      at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:68)
                      at com.android.tools.profiler.support.event.WindowProfilerCallback.dispatchTouchEvent(WindowProfilerCallback.java:69)
                      at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:376)
                      at android.view.View.dispatchPointerEvent(View.java:10177)
                      at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4492)
                      at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4357)
                      at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3897)
                      at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3950)
                      at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3916)
                      at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4043)
                      at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3924)
                      at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4100)
                      at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3897)
                      at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3950)
                      at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3916)
                      at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3924)
                      at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3897)
                      at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6268)
                      at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6242)
                      at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6203)
                      at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6374)
                      at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:187)
                      at android.os.MessageQueue.nativePollOnce(Native Method)
                      at android.os.MessageQueue.next(MessageQueue.java:323)
                      at android.os.Looper.loop(Looper.java:142)
E/AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java:6342)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:880)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:770)

**Comment by TusharSri** [comment]
Any help would be appreciated, Me to getting same stack trace and crash

**Comment by janishar** [comment]
@TusharSri I am looking into this... are you using SwipePlaceHolderView or SwipeDirectionalView

**Comment by zouhir98** [comment]
help i hv same error whene in shoce SwipeRefreshLayout
