### ISSUE TITLE
 Unable to find constructor for com.mindorks.demo.swipe.TinderCard

### ISSUE THREAD

**Issue by specloli** [janishar/PlaceHolderView#108]
Caused by: java.lang.RuntimeException: Unable to find constructor for com.mindorks.demo.swipe.TinderCard
                                                       at com.mindorks.placeholderview.Binding.getBinderInstance(Binding.java:47)
                                                       at com.mindorks.placeholderview.Binding.bindSwipeViewResolver(Binding.java:67)
                                                       at com.mindorks.placeholderview.SwipePlaceHolderView.getViewBinder(SwipePlaceHolderView.java:206)
                                                       at com.mindorks.placeholderview.SwipePlaceHolderView.addView(SwipePlaceHolderView.java:211)
                                                       at com.mindorks.demo.ActivityTinder.onPostCreate(ActivityTinder.java:71)
                                                       at android.app.Instrumentation.callActivityOnPostCreate(Instrumentation.java:1199)
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2647)
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726) 
                                                       at android.app.ActivityThread.-wrap12(ActivityThread.java) 
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477) 
                                                       at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                       at android.os.Looper.loop(Looper.java:154) 
                                                       at android.app.ActivityThread.main(ActivityThread.java:6119) 
                                                       at java.lang.reflect.Method.invoke(Native Method) 
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886) 
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776) 
                                                       at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:107)

**Comment by janishar** [comment]
@specloli rebuild the project

**Comment by xavierpellvidal** [comment]
same problem here... rebuild and restart android stuido and clean project not working.

**Comment by Jay268** [comment]
@janishar Same problem also rebuild and clean not working tried that but no luck. Can you please check into this issue. It is getting crashed immediate after launch app.

`FATAL EXCEPTION: main
                                                                 Process: com.mindorks.demo, PID: 4789
                                                                 java.lang.RuntimeException: Unable to start activity ComponentInfo{com.mindorks.demo/com.mindorks.demo.ActivityTinder}: java.lang.RuntimeException: Unable to find constructor for com.mindorks.demo.swipe.TinderCard
                                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2521)
                                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2595)
                                                                     at android.app.ActivityThread.access$800(ActivityThread.java:178)
                                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1470)
                                                                     at android.os.Handler.dispatchMessage(Handler.java:111)
                                                                     at android.os.Looper.loop(Looper.java:194)
                                                                     at android.app.ActivityThread.main(ActivityThread.java:5631)
                                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                                     at java.lang.reflect.Method.invoke(Method.java:372)
                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:959)
                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:754)
                                                                  Caused by: java.lang.RuntimeException: Unable to find constructor for com.mindorks.demo.swipe.TinderCard
                                                                     at com.mindorks.placeholderview.Binding.getBinderInstance(Binding.java:47)
                                                                     at com.mindorks.placeholderview.Binding.bindSwipeViewResolver(Binding.java:67)
                                                                     at com.mindorks.placeholderview.SwipePlaceHolderView.getViewBinder(SwipePlaceHolderView.java:206)
                                                                     at com.mindorks.placeholderview.SwipePlaceHolderView.addView(SwipePlaceHolderView.java:211)
                                                                     at com.mindorks.demo.ActivityTinder.onPostCreate(ActivityTinder.java:71)
                                                                     at android.app.Instrumentation.callActivityOnPostCreate(Instrumentation.java:1194)
                                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2497)
                                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2595) 
                                                                     at android.app.ActivityThread.access$800(ActivityThread.java:178) 
                                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1470) 
                                                                     at android.os.Handler.dispatchMessage(Handler.java:111) 
                                                                     at android.os.Looper.loop(Looper.java:194) 
                                                                     at android.app.ActivityThread.main(ActivityThread.java:5631) 
                                                                     at java.lang.reflect.Method.invoke(Native Method) 
                                                                     at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:959) 
                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:754) 
                                                                  Caused by: java.lang.NoSuchMethodException: <init> [class com.mindorks.demo.swipe.TinderCard]
                                                                     at java.lang.Class.getConstructor(Class.java:531)
                                                                     at java.lang.Class.getConstructor(Class.java:495)
                                                                     at com.mindorks.placeholderview.Binding.getBinderInstance(Binding.java:26)
                                                                     at com.mindorks.placeholderview.Binding.bindSwipeViewResolver(Binding.java:67) 
                                                                     at com.mindorks.placeholderview.SwipePlaceHolderView.getViewBinder(SwipePlaceHolderView.java:206) 
                                                                     at com.mindorks.placeholderview.SwipePlaceHolderView.addView(SwipePlaceHolderView.java:211) 
                                                                     at com.mindorks.demo.ActivityTinder.onPostCreate(ActivityTinder.java:71) 
                                                                     at android.app.Instrumentation.callActivityOnPostCreate(Instrumentation.java:1194) 
                                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2497) 
                                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2595) 
                                                                     at android.app.ActivityThread.access$800(ActivityThread.java:178) 
                                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1470) 
                                                                     at android.os.Handler.dispatchMessage(Handler.java:111) 
                                                                     at android.os.Looper.loop(Looper.java:194) 
                                                                     at android.app.ActivityThread.main(ActivityThread.java:5631) 
                                                                     at java.lang.reflect.Method.invoke(Native Method) 
                                                                     at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:959) 
                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:754) `

**Comment by janishar** [comment]
@Jay268 @xavierpellvidal which android studio version you are using?
Make sure you are on android studio version 3+

**Comment by xavierpellvidal** [comment]
Yes @janishar , I'm using Android Studio version 3.0.1

**Comment by janishar** [comment]
@xavierpellvidal  can you provide your app's build.gradle dependencies block code?

**Comment by xavierpellvidal** [comment]
Yes:

dependencies {
    compile fileTree(include: ['*.jar'], dir: 'libs')
    compile('com.amazonaws:aws-android-sdk-core:2.4.+') {
        exclude group: 'com.google.code.gson', module: 'gson'
    }
    compile('com.amazonaws:aws-android-sdk-s3:2.4.+') {
        exclude group: 'com.google.code.gson', module: 'gson'
    }
    compile('com.amazonaws:aws-android-sdk-cognito:2.4.+') {
        exclude group: 'com.google.code.gson', module: 'gson'
    }
    compile('com.github.greenfrvr:hashtag-view:1.2.1') {
        exclude group: 'com.google.guava'
    }
    compile project(':crop')
    compile project(':crop')
    compile project(':emoji')
    compile 'io.searchbox:jest-droid:2.0.3'
    compile 'com.google.firebase:firebase-messaging:11.4.0'
    compile 'com.google.firebase:firebase-database:11.4.0'
    compile 'com.google.firebase:firebase-auth:11.4.0'
    compile 'com.google.firebase:firebase-core:11.4.0'
    compile 'com.google.firebase:firebase-appindexing:11.4.0'
    compile 'com.google.firebase:firebase-invites:11.4.0'
    compile 'com.google.firebase:firebase-analytics:11.4.0'
    compile 'com.android.support:support-annotations:26.0.2'
    compile 'com.android.support:appcompat-v7:26.0.2'
    compile 'com.android.support:design:26.0.2'
    compile 'com.android.support:support-v4:26.0.2'
    compile 'com.makeramen:roundedimageview:2.2.1'
    compile 'com.google.android.gms:play-services-analytics:11.4.0'
    compile 'com.google.android.gms:play-services-maps:11.4.0'
    compile 'com.google.android.gms:play-services-places:11.4.0'
    compile 'com.google.android.gms:play-services-location:11.4.0'
    compile 'com.google.android.gms:play-services-auth:11.4.0'
    compile 'com.google.android.gms:play-services-ads:11.4.0'
    compile 'com.splunk.mint:mint:5.0.0'
    compile 'com.googlecode.libphonenumber:libphonenumber:5.5'
    compile 'com.android.support:multidex:1.0.1'
    compile 'com.github.chrisbanes:PhotoView:1.3.0'
    compile 'com.facebook.android:facebook-android-sdk:4.+'
    compile 'com.squareup.retrofit2:retrofit:2.2.0'
    compile 'com.squareup.retrofit2:converter-jackson:2.2.0'
    compile 'com.squareup.okhttp3:logging-interceptor:3.9.1'
    compile 'com.github.bumptech.glide:glide:4.6.1'
    compile 'jp.wasabeef:glide-transformations:3.1.1'
    compile 'com.mindorks:placeholderview:0.7.3'
    compile 'com.crystal:crystalrangeseekbar:1.1.3'
    compile 'com.github.MorochoRochaDarwin:WCViewPagerIndicators:3.0'
    compile 'com.appsflyer:af-android-sdk:4.8.8'
    testCompile 'junit:junit:4.12'
    compile name: 'adcolony-sdk-3.2.1', ext: 'aar'
    compile name: 'mmedia-6.4.0', ext: 'aar'
    compile name: 'mobvista_alphab', ext: 'aar'
    compile name: 'mobvista_appwall', ext: 'aar'
    compile name: 'mobvista_appwallext', ext: 'aar'
    compile name: 'mobvista_common', ext: 'aar'
    compile name: 'mobvista_interstitial', ext: 'aar'
    compile name: 'mobvista_mvdownloads', ext: 'aar'
    compile name: 'mobvista_mvjscommon', ext: 'aar'
    compile name: 'mobvista_mvnative', ext: 'aar'
    compile name: 'mobvista_nativeex', ext: 'aar'
    compile name: 'mobvista_offerwall', ext: 'aar'
    compile name: 'mobvista_playercommon', ext: 'aar'
    compile name: 'mobvista_reward', ext: 'aar'
    compile name: 'mobvista_videocommon', ext: 'aar'
    compile name: 'mobvista_videofeeds', ext: 'aar'
}

now i'm using the previouse version due to this error, so it was the same as this block but changing

**Comment by xavierpellvidal** [comment]
Yes:

dependencies {
    compile fileTree(include: ['*.jar'], dir: 'libs')
    compile('com.amazonaws:aws-android-sdk-core:2.4.+') {
        exclude group: 'com.google.code.gson', module: 'gson'
    }
    compile('com.amazonaws:aws-android-sdk-s3:2.4.+') {
        exclude group: 'com.google.code.gson', module: 'gson'
    }
    compile('com.amazonaws:aws-android-sdk-cognito:2.4.+') {
        exclude group: 'com.google.code.gson', module: 'gson'
    }
    compile('com.github.greenfrvr:hashtag-view:1.2.1') {
        exclude group: 'com.google.guava'
    }
    compile project(':crop')
    compile project(':crop')
    compile project(':emoji')
    compile 'io.searchbox:jest-droid:2.0.3'
    compile 'com.google.firebase:firebase-messaging:11.4.0'
    compile 'com.google.firebase:firebase-database:11.4.0'
    compile 'com.google.firebase:firebase-auth:11.4.0'
    compile 'com.google.firebase:firebase-core:11.4.0'
    compile 'com.google.firebase:firebase-appindexing:11.4.0'
    compile 'com.google.firebase:firebase-invites:11.4.0'
    compile 'com.google.firebase:firebase-analytics:11.4.0'
    compile 'com.android.support:support-annotations:26.0.2'
    compile 'com.android.support:appcompat-v7:26.0.2'
    compile 'com.android.support:design:26.0.2'
    compile 'com.android.support:support-v4:26.0.2'
    compile 'com.makeramen:roundedimageview:2.2.1'
    compile 'com.google.android.gms:play-services-analytics:11.4.0'
    compile 'com.google.android.gms:play-services-maps:11.4.0'
    compile 'com.google.android.gms:play-services-places:11.4.0'
    compile 'com.google.android.gms:play-services-location:11.4.0'
    compile 'com.google.android.gms:play-services-auth:11.4.0'
    compile 'com.google.android.gms:play-services-ads:11.4.0'
    compile 'com.splunk.mint:mint:5.0.0'
    compile 'com.googlecode.libphonenumber:libphonenumber:5.5'
    compile 'com.android.support:multidex:1.0.1'
    compile 'com.github.chrisbanes:PhotoView:1.3.0'
    compile 'com.facebook.android:facebook-android-sdk:4.+'
    compile 'com.squareup.retrofit2:retrofit:2.2.0'
    compile 'com.squareup.retrofit2:converter-jackson:2.2.0'
    compile 'com.squareup.okhttp3:logging-interceptor:3.9.1'
    compile 'com.github.bumptech.glide:glide:4.6.1'
    compile 'jp.wasabeef:glide-transformations:3.1.1'
    compile 'com.mindorks:placeholderview:0.7.3'
    compile 'com.crystal:crystalrangeseekbar:1.1.3'
    compile 'com.github.MorochoRochaDarwin:WCViewPagerIndicators:3.0'
    compile 'com.appsflyer:af-android-sdk:4.8.8'
    testCompile 'junit:junit:4.12'
    compile name: 'adcolony-sdk-3.2.1', ext: 'aar'
    compile name: 'mmedia-6.4.0', ext: 'aar'
    compile name: 'mobvista_alphab', ext: 'aar'
    compile name: 'mobvista_appwall', ext: 'aar'
    compile name: 'mobvista_appwallext', ext: 'aar'
    compile name: 'mobvista_common', ext: 'aar'
    compile name: 'mobvista_interstitial', ext: 'aar'
    compile name: 'mobvista_mvdownloads', ext: 'aar'
    compile name: 'mobvista_mvjscommon', ext: 'aar'
    compile name: 'mobvista_mvnative', ext: 'aar'
    compile name: 'mobvista_nativeex', ext: 'aar'
    compile name: 'mobvista_offerwall', ext: 'aar'
    compile name: 'mobvista_playercommon', ext: 'aar'
    compile name: 'mobvista_reward', ext: 'aar'
    compile name: 'mobvista_videocommon', ext: 'aar'
    compile name: 'mobvista_videofeeds', ext: 'aar'
}

I'm using the previous version so when this error occurs, I had the new plugin version lines:

compile 'com.mindorks.android:placeholderview:1.0.0'
annotationProcessor 'com.mindorks.android:placeholderview-compiler:1.0.0'

rather than de old:
compile 'com.mindorks:placeholderview:0.7.3'

**Comment by janishar** [comment]
This error is occuring using 
```groovy
compile 'com.mindorks.android:placeholderview:1.0.0'
annotationProcessor 'com.mindorks.android:placeholderview-compiler:1.0.0'
```
OR
```groovy
compile 'com.mindorks:placeholderview:0.7.3'
```

**Comment by Jay268** [comment]
@janishar Yes i am also using android studio version 3.0.1 and i am running your downloaded project itself and it's getting crashed on app launch any suggestions ? i didn't make any changes to any of the gradle files.

**Comment by xavierpellvidal** [comment]
@janishar is occurring using 

`compile 'com.mindorks.android:placeholderview:1.0.0'
annotationProcessor 'com.mindorks.android:placeholderview-compiler:1.0.0'`

**Comment by janishar** [comment]
I am not able to reproduce this error.

Can you try 
1. tools->android->sync project with gradle files
2. build -> clean project
3. build -> rebuild project

The same issue mentioned in the butterknife.
https://github.com/JakeWharton/butterknife/issues/778

**Comment by Jay268** [comment]
@janishar Tried with above mentioned steps but still it's crashing on start of app with same exception logs.

**Comment by rishi023** [comment]
@janishar, getting the same error. Cloned the branch and built the sample app and run it, but getting the error:
Caused by: java.lang.RuntimeException: Unable to find constructor for com.mindorks.demo.swipe.TinderCard  at com.mindorks.placeholderview.Binding.getBinderInstance(Binding.java:47) at com.mindorks.placeholderview.Binding.bindSwipeViewResolver(Binding.java:67) at com.mindorks.placeholderview.SwipePlaceHolderView.getViewBinder(SwipePlaceHolderView.java:206) at com.mindorks.placeholderview.SwipePlaceHolderView.addView(SwipePlaceHolderView.java:211) at com.mindorks.demo.ActivityTinder.onPostCreate(ActivityTinder.java:71)

**Comment by ericfjl** [comment]
I had the same error.

03-30 11:06:14.724 10734-10734/com.lee.hanzibishun W/System.err: java.lang.RuntimeException: Unable to find constructor for com.lee.hanzibishun.ui.wordcard.HzbWordCard
03-30 11:06:14.724 10734-10734/com.lee.hanzibishun W/System.err:     at com.mindorks.placeholderview.Binding.getBinderInstance(Binding.java:47)
03-30 11:06:14.724 10734-10734/com.lee.hanzibishun W/System.err:     at com.mindorks.placeholderview.Binding.bindSwipeViewResolver(Binding.java:67)
03-30 11:06:14.724 10734-10734/com.lee.hanzibishun W/System.err:     at com.mindorks.placeholderview.SwipePlaceHolderView.getViewBinder(SwipePlaceHolderView.java:206)
03-30 11:06:14.724 10734-10734/com.lee.hanzibishun W/System.err:     at com.mindorks.placeholderview.SwipePlaceHolderView.addView(SwipePlaceHolderView.java:211)
03-30 11:06:14.724 10734-10734/com.lee.hanzibishun W/System.err:     at com.lee.hanzibishun.ui.wordcard.WordCardActivity.initSwipView(WordCardActivity.java:371)
03-30 11:06:14.724 10734-10734/com.lee.hanzibishun W/System.err:     at com.lee.hanzibishun.ui.wordcard.WordCardActivity.onPostCreate(WordCardActivity.java:344)
03-30 11:06:14.724 10734-10734/com.lee.hanzibishun W/System.err:     at android.app.Instrumentation.callActivityOnPostCreate(Instrumentation.java:1187)
03-30 11:06:14.724 10734-10734/com.lee.hanzibishun W/System.err:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2432)
03-30 11:06:14.724 10734-10734/com.lee.hanzibishun W/System.err:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2512)
03-30 11:06:14.724 10734-10734/com.lee.hanzibishun W/System.err:     at android.app.ActivityThread.access$1200(ActivityThread.java:165)
03-30 11:06:14.724 10734-10734/com.lee.hanzibishun W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1373)
03-30 11:06:14.724 10734-10734/com.lee.hanzibishun W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
03-30 11:06:14.724 10734-10734/com.lee.hanzibishun W/System.err:     at android.os.Looper.loop(Looper.java:135)
03-30 11:06:14.724 10734-10734/com.lee.hanzibishun W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5593)
03-30 11:06:14.724 10734-10734/com.lee.hanzibishun W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
03-30 11:06:14.724 10734-10734/com.lee.hanzibishun W/System.err:     at java.lang.reflect.Method.invoke(Method.java:372)
03-30 11:06:14.724 10734-10734/com.lee.hanzibishun W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:968)
03-30 11:06:14.724 10734-10734/com.lee.hanzibishun W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:763)
03-30 11:06:14.724 10734-10734/com.lee.hanzibishun W/System.err: Caused by: java.lang.NoSuchMethodException: <init> [class com.lee.hanzibishun.ui.wordcard.HzbWordCard]
03-30 11:06:14.724 10734-10734/com.lee.hanzibishun W/System.err:     at java.lang.Class.getConstructor(Class.java:531)
03-30 11:06:14.724 10734-10734/com.lee.hanzibishun W/System.err:     at java.lang.Class.getConstructor(Class.java:495)
03-30 11:06:14.724 10734-10734/com.lee.hanzibishun W/System.err:     at com.mindorks.placeholderview.Binding.getBinderInstance(Binding.java:26)
03-30 11:06:14.724 10734-10734/com.lee.hanzibishun W/System.err: 	... 17 more

**Comment by ericfjl** [comment]
I had change the placeholderview:1.0.0 to placeholderview:0.7.3 ,It do work! why?

**Comment by TemMax** [comment]
+. I had the same issue. Android studio 3.1 and newest gradle. (Kotlin)

**Comment by janishar** [comment]
Can anyone with this issue verify that `app/build/generated/source/apt/`  for cloned `PlaceHolderView` looks similar to the below directory for `swipe` package?
debug
    └── com
        └── mindorks
            ├── demo
            │   ├── CardPresenter$DirectionalViewBinder.java
            │   ....
            │   └── swipe
            │       ├── SwipeCard$DirectionalViewBinder.java
            │       ├── SwipeCard$ExpandableViewBinder.java
            │       ├── SwipeCard$LoadMoreViewBinder.java
            │       ├── SwipeCard$SwipeViewBinder.java
            │       ├── SwipeCard$ViewBinder.java
            │       ├── TinderCard$DirectionalViewBinder.java
            │       ├── TinderCard$ExpandableViewBinder.java
            │       ├── TinderCard$LoadMoreViewBinder.java
            │       ├── TinderCard$SwipeViewBinder.java
            │       ├── TinderCard$ViewBinder.java
            │       ├── TinderCard2$DirectionalViewBinder.java
            │       ├── TinderCard2$ExpandableViewBinder.java
            │       ├── TinderCard2$LoadMoreViewBinder.java
            │       ├── TinderCard2$SwipeViewBinder.java
            │       ├── TinderCard2$ViewBinder.java
            │       ├── TinderDirectionalCard$DirectionalViewBinder.java
            │       ├── TinderDirectionalCard$ExpandableViewBinder.java
            │       ├── TinderDirectionalCard$LoadMoreViewBinder.java
            │       ├── TinderDirectionalCard$SwipeViewBinder.java
            │       └── TinderDirectionalCard$ViewBinder.java
            └── placeholderview
                └── $
                    └── R.java

**Comment by janishar** [comment]
Please update to version 1.0.2 and verify if the issue is resolved.
@specloli @xavierpellvidal @Jay268 @rishi023 @ericfjl 

This must be coming when `minify` was set to `true`. I have added the proguard rules for the same.

```gradle
dependencies {
    ...
    compile 'com.mindorks.android:placeholderview:1.0.2'
    annotationProcessor 'com.mindorks.android:placeholderview-compiler:1.0.2'
}
```

**Comment by hessio** [comment]
I am unable to get this library to work, I have followed the steps mentioned above about rebuilding, restarting, changing the dependencies, etc.
