### ISSUE TITLE
Unable to find constructor for HeadingView

### ISSUE THREAD

**Issue by HandsomeCoder** [janishar/PlaceHolderView#116]
```
@Parent
@SingleTop
@Layout(R.layout.feed_heading)
class HeadingView {

    @View(R.id.detail_heading_textView)
    TextView headingTxt;

    @View(R.id.toggleIcon)
    ImageView toggleIcon;

    @Toggle(R.id.heading_toggleView)
    LinearLayout toggleView;

    @ParentPosition
    int mParentPosition;

    private Context mContext;
    private int mHeading;


    HeadingView(Context mContext, int mHeading) {
        this.mContext = mContext;
        this.mHeading = mHeading;
    }

    @Resolve
    void onResolved() {
        toggleIcon.setImageDrawable(mContext.getResources().getDrawable(R.drawable.ic_arrow_down));
        headingTxt.setText(mHeading);
    }

    @Expand
    void onExpand() {
        toggleIcon.setImageDrawable(mContext.getResources().getDrawable(R.drawable.ic_arrow_up));
    }

    @Collapse
    void onCollapse() {
        toggleIcon.setImageDrawable(mContext.getResources().getDrawable(R.drawable.ic_arrow_down));
        System.gc();
    }

}
```

I have error that unable to find constructor when there is constructor in headindView and it is accessable

```
`     Caused by: java.lang.RuntimeException: Unable to find constructor for in.ac.charusat.charusat.fragments.HeadingView
        at com.mindorks.placeholderview.Binding.getBinderInstance(Binding.java:47)
        at com.mindorks.placeholderview.Binding.bindExpandableViewResolver(Binding.java:60)
        at com.mindorks.placeholderview.ExpandableViewAdapter.addView(ExpandableViewAdapter.java:25)
        at com.mindorks.placeholderview.PlaceHolderView.addView(PlaceHolderView.java:67)
        at in.ac.charusat.charusat.fragments.DetailFragment.onCreateView(DetailFragment.java:53)
        at android.support.v4.app.Fragment.performCreateView(Fragment.java:2343)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1421)
        at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1752)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1821)
        at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:797)
        at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2595)
````

**Comment by janishar** [comment]
@HandsomeCoder what is the library version you are using?
Please use >= 1.0.3
