### ISSUE TITLE
Reusing ExpandablePlaceHolderView

### ISSUE THREAD

**Issue by sergiobr** [janishar/PlaceHolderView#40]
In my code I need to clear ExpandablePlaceHolderView list content and reload new itens on there ate the same screen, beause I have a filter in that.
But seems it has some problem in clearing or notifying the adapter, since after I call expandableView.removeAllViews() and after add the new itens, it gives the following error:
  `08-02 12:06:26.721 15844-15844/ E/AndroidRuntime: FATAL EXCEPTION: main
                                                                         Process: , PID: 15844
                                                                         java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid item position 0(offset:11).state:6
                                                                             at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5504)
                                                                             at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5440)
                                                                             at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5436)
                                                                             at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2224)
                                                                             at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1551)
                                                                             at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1511)
                                                                             at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:595)
                                                                             at android.support.v7.widget.RecyclerView.dispatchLayoutStep1(RecyclerView.java:3534)
                                                                             at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3310)
                                                                             at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3844)
                                                                             at android.view.View.layout(View.java:19393)
                                                                             at android.view.ViewGroup.layout(ViewGroup.java:6022)
                                                                             at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1080)
                                                                             at android.view.View.layout(View.java:19393)
                                                                             at android.view.ViewGroup.layout(ViewGroup.java:6022)
                                                                             at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1791)
                                                                             at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1635)
                                                                             at android.widget.LinearLayout.onLayout(LinearLayout.java:1544)
                                                                             at android.view.View.layout(View.java:19393)
                                                                             at android.view.ViewGroup.layout(ViewGroup.java:6022)
                                                                             at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                                                                             at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                                                                             at android.view.View.layout(View.java:19393)
                                                                             at android.view.ViewGroup.layout(ViewGroup.java:6022)
                                                                             at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1791)
                                                                             at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1635)
                                                                             at android.widget.LinearLayout.onLayout(LinearLayout.java:1544)
                                                                             at android.view.View.layout(View.java:19393)
                                                                             at android.view.ViewGroup.layout(ViewGroup.java:6022)
                                                                             at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                                                                             at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                                                                             at android.view.View.layout(View.java:19393)
                                                                             at android.view.ViewGroup.layout(ViewGroup.java:6022)
                                                                             at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1791)
                                                                             at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1635)
                                                                             at android.widget.LinearLayout.onLayout(LinearLayout.java:1544)
                                                                             at android.view.View.layout(View.java:19393)
                                                                             at android.view.ViewGroup.layout(ViewGroup.java:6022)
                                                                             at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                                                                             at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                                                                             at com.android.internal.policy.DecorView.onLayout(DecorView.java:736)
                                                                             at android.view.View.layout(View.java:19393)
                                                                             at android.view.ViewGroup.layout(ViewGroup.java:6022)
                                                                             at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2480)
                                                                             at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2199)
                                                                             at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1385)
                                                                             at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6722)
                                                                             at android.view.Choreographer$CallbackRecord.run(Choreographer.java:886)
                                                                             at android.view.Choreographer.doCallbacks(Choreographer.java:698)
                                                                             at android.view.Choreographer.doFrame(Choreographer.java:633)
                                                                             at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:872)
                                                                             at android.os.Handler.handleCallback(Handler.java:769)
                                                                             at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                             at android.os.Looper.loop(Looper.java:164)
                                                                             at android.app.ActivityThread.main(ActivityThread.java:6540)
                                                                             at java.lang.reflect.Method.invoke(Native Method)
                                                                             at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
08-02 12:06:26.722 15844-15844/ E/AndroidRuntime:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
08-02 12:06:26.723 15844-15844/ E/UncaughtException: java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid item position 0(offset:11).state:6
                                                                                at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5504)
                                                                                at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5440)
                                                                                at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5436)
                                                                                at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2224)
                                                                                at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1551)
                                                                                at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1511)
                                                                                at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:595)
                                                                                at android.support.v7.widget.RecyclerView.dispatchLayoutStep1(RecyclerView.java:3534)
                                                                                at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3310)
                                                                                at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3844)
                                                                                at android.view.View.layout(View.java:19393)
                                                                                at android.view.ViewGroup.layout(ViewGroup.java:6022)
                                                                                at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1080)
                                                                                at android.view.View.layout(View.java:19393)
                                                                                at android.view.ViewGroup.layout(ViewGroup.java:6022)
                                                                                at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1791)
                                                                                at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1635)
                                                                                at android.widget.LinearLayout.onLayout(LinearLayout.java:1544)
                                                                                at android.view.View.layout(View.java:19393)
                                                                                at android.view.ViewGroup.layout(ViewGroup.java:6022)
                                                                                at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                                                                                at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                                                                                at android.view.View.layout(View.java:19393)
                                                                                at android.view.ViewGroup.layout(ViewGroup.java:6022)
                                                                                at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1791)
                                                                                at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1635)
                                                                                at android.widget.LinearLayout.onLayout(LinearLayout.java:1544)
                                                                                at android.view.View.layout(View.java:19393)
                                                                                at android.view.ViewGroup.layout(ViewGroup.java:6022)
                                                                                at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                                                                                at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                                                                                at android.view.View.layout(View.java:19393)
                                                                                at android.view.ViewGroup.layout(ViewGroup.java:6022)
                                                                                at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1791)
                                                                                at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1635)
                                                                                at android.widget.LinearLayout.onLayout(LinearLayout.java:1544)
                                                                                at android.view.View.layout(View.java:19393)
                                                                                at android.view.ViewGroup.layout(ViewGroup.java:6022)
                                                                                at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                                                                                at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                                                                                at com.android.internal.policy.DecorView.onLayout(DecorView.java:736)
                                                                                at android.view.View.layout(View.java:19393)
                                                                                at android.view.ViewGroup.layout(ViewGroup.java:6022)
                                                                                at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2480)
                                                                                at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2199)
                                                                                at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1385)
                                                                                at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6722)
                                                                                at android.view.Choreographer$CallbackRecord.run(Choreographer.java:886)
                                                                                at android.view.Choreographer.doCallbacks(Choreographer.java:698)
                                                                                at android.view.Choreographer.doFrame(Choreographer.java:633)
                                                                                at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:872)
                                                                                at android.os.Handler.handleCallback(Handler.java:769)
                                                                                at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                                at android.os.Looper.loop(Looper.java:164)
                                                                                at android.app.ActivityThread.main(ActivityThread.java:6540)
                                                                                at java.lang.reflect.Method.invoke(Native Method)
                                                                                at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
                                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)`

**Comment by sergiobr** [comment]
I added expandableView.getAdapter().notifyDataSetChanged(); and it works.

**Comment by janishar** [comment]
@sergiobr I will fix the bug soon thanks

**Comment by janishar** [comment]
@sergiobr This issue has already been resolved. Please refer to this issue: https://github.com/janishar/PlaceHolderView/issues/34

Use for fix:
```groovy
compile 'com.mindorks:placeholderview:0.6.5'
```

**Comment by sergiobr** [comment]
Thank you @janishar
